### PR TITLE
Add "How to Code Neat Machine Learning Pipelines" post.

### PR DESCRIPTION
**Pull request by guillaume-chevalier**

### CODE REVIEW

**Comment by chblw** [comment]
Maybe a better title would be _How to use Neuraxle_ ? Most pipeline work can be done with sklearn so you might want to motivate more why to use Neuraxle vs sklearn. 

Also, this looks like a copy of your other [other ML blog](https://www.neuraxio.com/en/blog/neuraxle/2019/10/26/neat-machine-learning-pipelines.html). Do we want exclusively OC on this blog ? @samperochkin @stecaron @davebulaval

**Comment by stecaron** [comment]
I'm not against reusing some other content to share posts on our end. However, I agree with @chblw that it would be nice having a small "touch" to make the post fits better in .Layer blog.

I have not read the article so far. @davebulaval has a good point by saying we don't want to make "pub", but it could be OK to say a word or two about a business. It's a matter of balance in my sense ..

**Comment by chblw** [comment]
When sharing personal work, I think the vibe from articles should be _look what I did_ instead of _this is why you should use what I did_. 

The ideas in the post are interesting, but the post is not written for the .Layer audience imo. 

Maybe a better structure would be : I think ml pipelines should contain ... (bulk of ideas). Btw, I implemented these concepts in Neuraxle, (with a plug to your company / library at the end).

**Comment by guillaume-chevalier** [comment]
@davebulaval indeed there are lots of references. I linked to the documentation website to the proper places documenting discussed features for people to be able to learn how to implement them. There is actually only 1 link to my blog for subscribers, a mailto link for direct contact, and the rest is either metadata or links to documentation. 

@davebulaval If you want to see this blog promote something, go read the article named "We mastered the art of programming", this one looks like self-promotion. Okay, this post has a funny tone so it is well-received, and I don't intend to start a fight, althought if you look closely, most of this other post is self-promotion but written in a funny/friendly vibe. 

@chblw You say:

> Maybe a better structure would be : I think ml pipelines should contain ... (bulk of ideas). Btw, I implemented these concepts in Neuraxle, (with a plug to your company / library at the end).

I like this idea. I think the article is already like that: 
1. Despite the links to the documentation website pointing to the discussed functions implementing the discussed features, the name of the library, "Neuraxle", appears only 7 times in the article, which is not much if we rename the article "How to use Neuraxle". 
2. The only links to Neuraxio are at the end of the article. See full info here: 

To be precise, here is an analysis of the "25 links". There are in fact 24, and the link to the company's blog is already only at the end (below the big image to be precise): 
- _20 links are pointing towards the Neuraxle documentation. That is legit considering this post is intended to be a tutorial._
- _1 link is an image statically hosted on neuraxio.com. It could be moved here to ensure the link don't change._
- _1 link is for the `<head>` of this post specifically to point to the original post. It was intended for this post to be a clone of the other one, I've discussed this already with @stecaron earlier (see how the header changed in the changes files list - it is planned that the article be a crosspost of the original one)._ 
- __1 link at the end points to the blog.__
- __1 link at the end is a `mailto:hello@neuraxio.com` for direct contact.__

Note that most of this will move to another website in the future (links are fine, there will be proper redirection), and it will feel less like a business, and more like an open-source project. This is already planned, and it will avoid having harsh comments like the one of @davebulaval. This stuff is truly open-source. And it is even `permissive` open-source, unlike GPL-licensed code. The article is mostly informational if you consider the links are to the documentation. 

@chblw Good suggestion for the name of the article. Although I won't rename my original article's name, I can rename this one. I also like your suggestion on the tone "I think ml pipelines should contain"

__To sum up:__

In the end, I believe this article is fine. @chblw and @stecaron, Maybe that the blunt and uninformed comment of @davebulaval influenced your thought process. There is no selling of services in the current article, and no self-promotion. Mostly reasons why you should use certain design patterns and methods and ways to structure your objects in your code, and we show how we did it with Neuraxle. 

@chblw and @stecaron That said, regarding the vibe of the article. What would you request at that point? I think you could go ahead and review the article. There is in fact only link to the company at the end below the last image in the last two sentence. The rest is pointing to documentation, and the name of the library is said max 7 times (which is not much if we rename the article with the suggested name). 

Thank you @davebulaval for your very informed negative comment.

**Comment by guillaume-chevalier** [comment]
@chblw Hey, interesting idea you've got here: 

> Most pipeline work can be done with sklearn so you might want to motivate more why to use Neuraxle vs sklearn.

I think that would be for another article. This one is already too long (it could be splitted in two different articles already I think). 

Explained quickly: 
- It is hard to have nested sklearn pipelines (pipelines within pipelines as pipeline steps). For instance, model stacking might require nested pipelines. That is at least mentionned in the article I think. 
- sklearn steps doesn't have ranges for the hyperparameters. Neuraxle steps have that, so it's possible to do hyperparameter tuning at a pipeline level even with nested objects (pipelines in pipelines) and so forth. 
- in sklearn, hyperparameters absolutely must be constructor arguments, otherwise the sklearn objects will break
- sklearn is not really made for code using GPU: it is assumed everything can be threaded and serialized with joblib. With Neuraxle, there is more freedom and each step of the pipeline can specify a way to override the default serialization mechanism, which allows for easier saving of GPU models and easier parallelization. 

Some of those reasons are already transparent in the present article. 

Also, there are some things that can't be fixed in scikit-learn because of choices they made years ago even if they'd want to fix that now. The author of scikit-learn itself suggests in one of his own talks that it would be good that some things be done in other independent libraries to improve that. Here is the [pertinent excerpt](https://www.youtube.com/embed/Wy6EKjJT79M?start=1361&end=1528) from his talk. Neuraxle aims at fixing this, it is a layer of code to be used on top of sklearn. 

@chblw If you really want, I could add a little section for that at the beginning, explaining what I've just listed. I'd prefer writing another article solely on that, thought.

**Comment by davebulaval** [comment]
> @davebulaval If you want to see this blog promote something, go read the article named "We mastered the art of programming", this one looks like self-promotion. Okay, this post has a funny tone so it is well-received, and I don't intend to start a fight, althought if you look closely, most of this other post is self-promotion but written in a funny/friendly vibe.
> 
What are you talking about his self-promotion ? 
It's an experience post to deconstruct our tendancy to think we hare the best in everyting (specially actuary).  It's far from a self-promoting, he don't event offer is service or else.


Explain me how pointing to a framework you develop with Neuraxio is not a self-promotion ? 
Explain me how the citation of other alternatives only appear at the end of the article?
Explain me how adding the fork to our organization GitHub of Neuraxle is appropriated?

The propose approach by @chblw is far more interessting. The prblem of pipeline in a ML work is definitely a *real* problem. But, you stated the problem in about 10 lines, you jump to what is pipeline and after that you explain method of your pipeline. Never explaining that THIS is your propose solution, you plug the doc of Neuraxle after around 40 lines. 

Talking about the real reason of the pipeline problem and real reason to use it its good and it also can be done with less promotion to your work.


> At Neuraxio, we’ve never seen someone tell us that they’d prefer to play with the caching of the data instead of coding the neural network.
This got me trigger.

**Comment by davebulaval** [comment]
> @chblw Hey, interesting idea you've got here:
> 
> > Most pipeline work can be done with sklearn so you might want to motivate more why to use Neuraxle vs sklearn.
> 
> I think that would be for another article. This one is already too long (it could be splitted in two different articles already I think).

Because this post is more about showing the doc. I think the first one should be stating the problem of workflow and else. Explaining that using piplines is one of the solution. And showing some framework that can be use to solved this problem.

And as a second article, SKlean vs Neuraxle.

**Comment by chblw** [comment]
I read the article more attentively, and it's very good content. You have a good understanding of pipelines, and that would benefit our community. 

Unfortunately, the first impression I got from the article was that it's self-promoting, probably because I don't have a good grasp of the difference between Neuraxle and Neuraxio. What I didn't like is that you provide documentation to Neuraxle and not sklearn without mentioning why. Someone who already used sklearn would wonder why you don't promote the most popular framework. Maybe provide a link to documentation from sklearn _and_ Neuraxio would pass as more honest. When writing for a blog, you're fighting for attention, and first impressions can have a big impact. 

I agree with @guillaume-chevalier and @davebulaval that it should be split into two articles. It's quite long and goes quickly in detail. Here's how I see it :

**Article 1:** I see your introduction and the WHAT ARE PIPELINES? section one article. Along with a real-life case study example using sklearn or Neuraxle, I think the community would benefit from this. You could end by stating the flaws of sklearn or listing good practices in pipelines, leading to a second article. 

**Article 2:** Present your framework from the point of view _This is my attempt to improving pipelines_ instead of _This is the right way to code pipelines_. Currently, your tone seems to claim you solved the pipeline issue. Bringing it back to @jtbai's post, we never actually learn how to write good code, but we strive to improve. 

That being said, the checkpoint, competition code and data streaming sections could all be standalone articles.

**Comment by AnnieDeshaies** [comment]
Guillaume, je ne pense pas que c'est approprie de critiquer les commentaires de David en utilisant les termes blunt et uninformed. Apprends a prendre la critique, c'est pas grave si les gars te demandent de changer des affaires. Ils ont travailles fort pour starter les meetups, les podcasts, le blog... seems legit to me qu'ils te demandent de changer des affaires qu'ils aiment moins? En programmation, on passe notre temps a efface et reecrire du code, c'est pas grave, ca veut pas dire que l'article est mauvais.

**Comment by ngarneau** [comment]
> I read the article more attentively, and it's very good content. You have a good understanding of pipelines, and that would benefit our community.
> 
> Unfortunately, the first impression I got from the article was that it's self-promoting, probably because I don't have a good grasp of the difference between Neuraxle and Neuraxio. What I didn't like is that you provide documentation to Neuraxle and not sklearn without mentioning why. Someone who already used sklearn would wonder why you don't promote the most popular framework. Maybe provide a link to documentation from sklearn _and_ Neuraxio would pass as more honest. When writing for a blog, you're fighting for attention, and first impressions can have a big impact.
> 
> I agree with @guillaume-chevalier and @davebulaval that it should be split into two articles. It's quite long and goes quickly in detail. Here's how I see it :
> 
> **Article 1:** I see your introduction and the WHAT ARE PIPELINES? section one article. Along with a real-life case study example using sklearn or Neuraxle, I think the community would benefit from this. You could end by stating the flaws of sklearn or listing good practices in pipelines, leading to a second article.
> 
> **Article 2:** Present your framework from the point of view _This is my attempt to improving pipelines_ instead of _This is the right way to code pipelines_. Currently, your tone seems to claim you solved the pipeline issue. Bringing it back to @jtbai's post, we never actually learn how to write good code, but we strive to improve.
> 
> That being said, the checkpoint, competition code and data streaming sections could all be standalone articles.

Really good review @chblw!

**Comment by guillaume-chevalier** [comment]
@AnnieDeshaies J'aime bien la critique de @chblw, c'est constructif ça :smiley: Je pointe plutôt @davebulaval qui a commenté de façon purement négative, non-constructive, mais en plus, erronée, et qui me faisait paraître comme ayant des intentions de promotion démesurées. @chblw a bien lu l'article et a seulement fait des commentaires constructifs jusqu'à présent, ce que je trouve bien, je suis content qu'il suggère des améliorations, actuellement il a plusieurs idées intéressantes.

**Comment by guillaume-chevalier** [comment]
@chblw Yes, good idea: 
> Article 1: I see your introduction and the WHAT ARE PIPELINES? section one article. Along with a real-life case study example using sklearn or Neuraxle, I think the community would benefit from this. You could end by stating the flaws of sklearn or listing good practices in pipelines, leading to a second article.
> 
> Article 2: Present your framework from the point of view This is my attempt to improving pipelines instead of This is the right way to code pipelines. Currently, your tone seems to claim you solved the pipeline issue. Bringing it back to @jtbai's post, we never actually learn how to write good code, but we strive to improve.
> 
> That being said, the checkpoint, competition code and data streaming sections could all be standalone articles.

I suggest: 

1. Article 1 - `What are ML pipelines?`: in this post, I'd first explain the basics, and then point to flaws of sklearn, suggest a Neuraxle solution and more importantly **why** not use sklearn in the given context. What I like in the suggestion of @chblw is that we should start with `why`. Why should things change?
2. Article 2 - `My suggestion on improving ML pipelines`: Okay, deep dive in the core of the article. This one explains in more detail the additions introduced by Neuraxle and the attempt to make ML code better. I'd prefer keeping an authoritative/formal tone in this article, precisely in the writing style of [Clean Code](https://s.s-bol.com/imgbase0/imagebase3/backcover/large/FC/1/7/2/3/1001004006133271.jpg), I think my "attempt" to improve pipelines is working (I use Neuraxle in many projects already and couldn't code without it already). I couldn't speak of it as a mere "attempt", but it can be a "suggestion" for the least.  
3. Article 3 - `Tearing down competition code`: this would make a quite funky/cool article, criticizing how most machine learning pipelines online aren't suitable for production usage and why. I could even cite some passages from the said code and expose how much it's bad. This is the jackass article written in an informal way. Sorry authors of competition code. I'd even criticize my own [competition code](https://github.com/guillaume-chevalier/CSGames-2019-AI) and slap myself in such an article. We might find a better name for the article until then. I may write it and post it only later, let's see. 
4. Checkpoint: let's keep this one on the backburner for later. Will contain massive improvements. 
5. Data Streaming: let's keep this one on the backburner for later. Will contain massive improvements. 

@chblw I'd open each PR in advance for articles 1 & 2, and perhaps even article 3. That'll require me to edit the text more to make it shorter and change the tone. I'll change this PR ton contain only article 1. Sounds good?

**Comment by chblw** [comment]
Yeah let's start with that @guillaume-chevalier. The audience for the first one should be someone who never used pipelines, while the second should be people who use them regularly. 

I agree the second could have a more formal tone.

**Comment by guillaume-chevalier** [comment]
@davebulaval, you say that this triggered you: 
> At Neuraxio, we’ve never seen someone tell us that they’d prefer to play with the caching of the data instead of coding the neural network.

I replaced this with: 

> I’ve never seen someone tell me that they’d prefer to play with the caching of the data instead of coding the neural network. Admit it - you just want to code the crunchy algorithms and want the rest done for you. Don't you?

The article's only reference to Neuraxio is now in the last 2 sentences and as a link to the original blog rather than as a textual reference. Neuraxio is actually never stated in the article. The only links are to the documentation now, and at the last 2 sentences. I'm sorry for your extreme anti-cooperativeness. Neuraxle is still a permissively-licensed and friendly open-source project, and it will stay like that. Thank you.

**Comment by guillaume-chevalier** [comment]
@chblw Thank you, I'll soon do the changes :raised_hands:

**Comment by davebulaval** [comment]
> @davebulaval, you say that this triggered you:
> 
> > At Neuraxio, we’ve never seen someone tell us that they’d prefer to play with the caching of the data instead of coding the neural network.
> 
> I replaced this with:
> 
> > I’ve never seen someone tell me that they’d prefer to play with the caching of the data instead of coding the neural network. Admit it - you just want to code the crunchy algorithms and want the rest done for you. Don't you?
> 
> The article's only reference to Neuraxio is now in the last 2 sentences and as a link to the original blog rather than as a textual reference. Neuraxio is actually never stated in the article. The only links are to the documentation now, and at the last 2 sentences. I'm sorry for your extreme anti-corporatism. Neuraxle is still a permissively-licensed and friendly open-source project, and it will stay like that. Thank you.

<3 Way more interessting.

**Comment by guillaume-chevalier** [comment]
Improvements: 
- Moved Neuraxle to a .org site
- The only mention to Neuraxio is now in the last mini-paragraph
- Removed all the rant about Kaggle competitions (for another article maybe) to make things shorter

Things that could probably be improved: 
- Did not link back to the "what's wrong with scikit-learn article" yet
- Could probably skip the section on parallelism and do an article just on that later on (as it's in the process of being [merged](https://github.com/Neuraxio/Neuraxle/pull/242) right now anyway and we could review what we said with practical examples).

**Comment by samperochkin** [comment]
Se passe quoi avec ça pals? @guillaume-chevalier comment tu vois ça?

**Comment by guillaume-chevalier** [comment]
@samperochkin je n'ai pas retouché à l'article correspondant sur le blog de neuraxio, le tout est plutôt stable: 
https://www.neuraxio.com/en/blog/neuraxle/2019/10/26/neat-machine-learning-pipelines.html

C'est notre article qui performe le mieux sur notre blogue Neuraxio. Je mergerais tel quel sans l'ajout proposé de deleter les commentaires sur le parallélisme, mais l'article semble pas etre listé quand je check le netlify CI preview, il semble y avoir un bug. 

Si j'ouvre un prochain article sur le parallélisme, à ce moment là je proposerai de modifier l'article présent en même temps pour pas doubler l'info. 

@davebulaval

**Comment by samperochkin** [comment]
Je te (nous) reviens là-dessus bien vite!

**Comment by freud14** [comment]
I would suggest to close this PR since the article was published in another.

**Pull request closed without merging**
